//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 01:32:25 PM AEDT 
//


package com.ibm.msl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * A <i>Field</i> is used within the definition of a <i>sort</i> mapping.
 * 
 * <b>attributes</b>
 * <ul>
 * <li><i>caseOrder</i></li>
 * <li><i>dataOrder</i></li>
 * <li><i>modifier</i></li>
 * <li><i>path</i></li>
 * </ul>
 *       
 * 
 * <p>Java class for Field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="caseOrder">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="lowerFirst"/>
 *             &lt;enumeration value="upperFirst"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dataOrder" default="lexical">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="lexical"/>
 *             &lt;enumeration value="numerical"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="modifier" default="ASC">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ASC"/>
 *             &lt;enumeration value="DESC"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field", propOrder = {
    "content"
})
public class Field {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "caseOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String caseOrder;
    @XmlAttribute(name = "dataOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataOrder;
    @XmlAttribute(name = "modifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String modifier;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * 
     * A <i>Field</i> is used within the definition of a <i>sort</i> mapping.
     * 
     * <b>attributes</b>
     * <ul>
     * <li><i>caseOrder</i></li>
     * <li><i>dataOrder</i></li>
     * <li><i>modifier</i></li>
     * <li><i>path</i></li>
     * </ul>
     *       
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the caseOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseOrder() {
        return caseOrder;
    }

    /**
     * Sets the value of the caseOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseOrder(String value) {
        this.caseOrder = value;
    }

    /**
     * Gets the value of the dataOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOrder() {
        if (dataOrder == null) {
            return "lexical";
        } else {
            return dataOrder;
        }
    }

    /**
     * Sets the value of the dataOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOrder(String value) {
        this.dataOrder = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifier() {
        if (modifier == null) {
            return "ASC";
        } else {
            return modifier;
        }
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifier(String value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
