//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 01:32:25 PM AEDT 
//


package com.ibm.msl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * A <i>Generation</i> provides properties of the
 * target execution engine for the map. 
 *       
 * 
 * <p>Java class for Generation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Generation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ibm.com/2008/ccl/Mapping}options" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="availableEngines" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="engine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaAware" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="derived" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Generation", propOrder = {
    "options"
})
public class Generation {

    protected Options options;
    @XmlAttribute(name = "availableEngines")
    protected String availableEngines;
    @XmlAttribute(name = "engine")
    protected String engine;
    @XmlAttribute(name = "schemaAware")
    protected Boolean schemaAware;
    @XmlAttribute(name = "derived")
    protected Boolean derived;

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
    public void setOptions(Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the availableEngines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailableEngines() {
        return availableEngines;
    }

    /**
     * Sets the value of the availableEngines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailableEngines(String value) {
        this.availableEngines = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngine(String value) {
        this.engine = value;
    }

    /**
     * Gets the value of the schemaAware property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSchemaAware() {
        return schemaAware;
    }

    /**
     * Sets the value of the schemaAware property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSchemaAware(Boolean value) {
        this.schemaAware = value;
    }

    /**
     * Gets the value of the derived property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDerived() {
        return derived;
    }

    /**
     * Sets the value of the derived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDerived(Boolean value) {
        this.derived = value;
    }

}
