//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 01:32:25 PM AEDT 
//


package com.ibm.msl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * An <i>Options</i> provides properties of the
 * <i>Generation</i>. 
 *       
 * 
 * <p>Java class for Options complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Options">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="indent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="indent-amount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="strip-space" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Options")
public class Options {

    @XmlAttribute(name = "indent")
    protected String indent;
    @XmlAttribute(name = "indent-amount")
    protected String indentAmount;
    @XmlAttribute(name = "strip-space")
    protected String stripSpace;

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndent() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndent(String value) {
        this.indent = value;
    }

    /**
     * Gets the value of the indentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndentAmount() {
        return indentAmount;
    }

    /**
     * Sets the value of the indentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndentAmount(String value) {
        this.indentAmount = value;
    }

    /**
     * Gets the value of the stripSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStripSpace() {
        return stripSpace;
    }

    /**
     * Sets the value of the stripSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStripSpace(String value) {
        this.stripSpace = value;
    }

}
