//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.15 at 08:03:36 PM AEDT 
//


package com.ibm.dictionary;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MAPDef">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="src_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="src_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="src_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trg_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trg_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trg_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubstMapping" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="src_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trg_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="spare1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="spare2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mapDef",
    "substMapping"
})
@XmlRootElement(name = "DictionaryCSV")
public class DictionaryCSV {

    @XmlElement(name = "MAPDef", required = true)
    public DictionaryCSV.MAPDef mapDef; //@DA changed to public from protected
    @XmlElement(name = "SubstMapping", required = true)
    public List<DictionaryCSV.SubstMapping> substMapping; //@DA changed to public from protected

    /**
     * Gets the value of the mapDef property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryCSV.MAPDef }
     *     
     */
    public DictionaryCSV.MAPDef getMAPDef() {
        return mapDef;
    }

    /**
     * Sets the value of the mapDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryCSV.MAPDef }
     *     
     */
    public void setMAPDef(DictionaryCSV.MAPDef value) {
        this.mapDef = value;
    }

    /**
     * Gets the value of the substMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DictionaryCSV.SubstMapping }
     * 
     * 
     */
    public List<DictionaryCSV.SubstMapping> getSubstMapping() {
        if (substMapping == null) {
            substMapping = new ArrayList<DictionaryCSV.SubstMapping>();
        }
        return this.substMapping;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="src_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="src_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="src_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trg_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trg_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trg_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srcSchema",
        "srcMessage",
        "srcParser",
        "trgSchema",
        "trgMessage",
        "trgParser"
    })
    public static class MAPDef {

        @XmlElement(name = "src_schema", required = true)
        public String srcSchema; //@DA protected to public for all
        @XmlElement(name = "src_message", required = true)
        public String srcMessage;
        @XmlElement(name = "src_parser", required = true)
        public String srcParser;
        @XmlElement(name = "trg_schema", required = true)
        public String trgSchema;
        @XmlElement(name = "trg_message", required = true)
        public String trgMessage;
        @XmlElement(name = "trg_parser", required = true)
        public String trgParser;

        /**
         * Gets the value of the srcSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcSchema() {
            return srcSchema;
        }

        /**
         * Sets the value of the srcSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcSchema(String value) {
            this.srcSchema = value;
        }

        /**
         * Gets the value of the srcMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcMessage() {
            return srcMessage;
        }

        /**
         * Sets the value of the srcMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcMessage(String value) {
            this.srcMessage = value;
        }

        /**
         * Gets the value of the srcParser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcParser() {
            return srcParser;
        }

        /**
         * Sets the value of the srcParser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcParser(String value) {
            this.srcParser = value;
        }

        /**
         * Gets the value of the trgSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrgSchema() {
            return trgSchema;
        }

        /**
         * Sets the value of the trgSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrgSchema(String value) {
            this.trgSchema = value;
        }

        /**
         * Gets the value of the trgMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrgMessage() {
            return trgMessage;
        }

        /**
         * Sets the value of the trgMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrgMessage(String value) {
            this.trgMessage = value;
        }

        /**
         * Gets the value of the trgParser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrgParser() {
            return trgParser;
        }

        /**
         * Sets the value of the trgParser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrgParser(String value) {
            this.trgParser = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="src_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trg_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="spare1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="spare2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srcField",
        "trgField",
        "spare1",
        "spare2",
        "description"
    })
    public static class SubstMapping {

        @XmlElement(name = "src_field", required = true)
        public String srcField; //@DA changed protected to public for all
        @XmlElement(name = "trg_field", required = true)
        public String trgField;
        @XmlElement(required = true)
        public String spare1;
        public String spare2;
        public String description;

        /**
         * Gets the value of the srcField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcField() {
            return srcField;
        }

        /**
         * Sets the value of the srcField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcField(String value) {
            this.srcField = value;
        }

        /**
         * Gets the value of the trgField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrgField() {
            return trgField;
        }

        /**
         * Sets the value of the trgField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrgField(String value) {
            this.trgField = value;
        }

        /**
         * Gets the value of the spare1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpare1() {
            return spare1;
        }

        /**
         * Sets the value of the spare1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpare1(String value) {
            this.spare1 = value;
        }

        /**
         * Gets the value of the spare2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpare2() {
            return spare2;
        }

        /**
         * Sets the value of the spare2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpare2(String value) {
            this.spare2 = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }

}
