//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BackupLocation.File"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Switch" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="When" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "backupLocationFile"
})
@XmlRootElement(name = "Backup")
public class Backup {

    @XmlElement(name = "BackupLocation.File", required = true)
    protected BackupLocationFile backupLocationFile;
    @XmlAttribute(name = "Switch")
    protected String _switch;
    @XmlAttribute(name = "When")
    protected String when;

    /**
     * Gets the value of the backupLocationFile property.
     * 
     * @return
     *     possible object is
     *     {@link BackupLocationFile }
     *     
     */
    public BackupLocationFile getBackupLocationFile() {
        return backupLocationFile;
    }

    /**
     * Sets the value of the backupLocationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackupLocationFile }
     *     
     */
    public void setBackupLocationFile(BackupLocationFile value) {
        this.backupLocationFile = value;
    }

    /**
     * Gets the value of the switch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitch() {
        return _switch;
    }

    /**
     * Sets the value of the switch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitch(String value) {
        this._switch = value;
    }

    /**
     * Gets the value of the when property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhen(String value) {
        this.when = value;
    }

}
