//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TraceLocation.File"/>
 *         &lt;choice>
 *           &lt;element ref="{}InputContentTrace.ALL"/>
 *           &lt;element ref="{}InputContentTrace.CARD"/>
 *           &lt;element ref="{}InputContentTrace.RANGE"/>
 *           &lt;element ref="{}InputContentTrace.OFF"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}RulesTrace.ALL"/>
 *           &lt;element ref="{}RulesTrace.CARD"/>
 *           &lt;element ref="{}RulesTrace.OFF"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}SummaryContentTrace.ON"/>
 *           &lt;element ref="{}SummaryContentTrace.OFF"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Switch" default="OFF">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ON"/>
 *             &lt;enumeration value="OFF"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "traceLocationFile",
    "inputContentTraceALL",
    "inputContentTraceCARD",
    "inputContentTraceRANGE",
    "inputContentTraceOFF",
    "rulesTraceALL",
    "rulesTraceCARD",
    "rulesTraceOFF",
    "summaryContentTraceON",
    "summaryContentTraceOFF"
})
@XmlRootElement(name = "ContentTrace.File")
public class ContentTraceFile {

    @XmlElement(name = "TraceLocation.File", required = true)
    protected TraceLocationFile traceLocationFile;
    @XmlElement(name = "InputContentTrace.ALL")
    protected InputContentTraceALL inputContentTraceALL;
    @XmlElement(name = "InputContentTrace.CARD")
    protected InputContentTraceCARD inputContentTraceCARD;
    @XmlElement(name = "InputContentTrace.RANGE")
    protected InputContentTraceRANGE inputContentTraceRANGE;
    @XmlElement(name = "InputContentTrace.OFF")
    protected InputContentTraceOFF inputContentTraceOFF;
    @XmlElement(name = "RulesTrace.ALL")
    protected RulesTraceALL rulesTraceALL;
    @XmlElement(name = "RulesTrace.CARD")
    protected RulesTraceCARD rulesTraceCARD;
    @XmlElement(name = "RulesTrace.OFF")
    protected RulesTraceOFF rulesTraceOFF;
    @XmlElement(name = "SummaryContentTrace.ON")
    protected SummaryContentTraceON summaryContentTraceON;
    @XmlElement(name = "SummaryContentTrace.OFF")
    protected SummaryContentTraceOFF summaryContentTraceOFF;
    @XmlAttribute(name = "Switch")
    protected String _switch;

    /**
     * Gets the value of the traceLocationFile property.
     * 
     * @return
     *     possible object is
     *     {@link TraceLocationFile }
     *     
     */
    public TraceLocationFile getTraceLocationFile() {
        return traceLocationFile;
    }

    /**
     * Sets the value of the traceLocationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraceLocationFile }
     *     
     */
    public void setTraceLocationFile(TraceLocationFile value) {
        this.traceLocationFile = value;
    }

    /**
     * Gets the value of the inputContentTraceALL property.
     * 
     * @return
     *     possible object is
     *     {@link InputContentTraceALL }
     *     
     */
    public InputContentTraceALL getInputContentTraceALL() {
        return inputContentTraceALL;
    }

    /**
     * Sets the value of the inputContentTraceALL property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputContentTraceALL }
     *     
     */
    public void setInputContentTraceALL(InputContentTraceALL value) {
        this.inputContentTraceALL = value;
    }

    /**
     * Gets the value of the inputContentTraceCARD property.
     * 
     * @return
     *     possible object is
     *     {@link InputContentTraceCARD }
     *     
     */
    public InputContentTraceCARD getInputContentTraceCARD() {
        return inputContentTraceCARD;
    }

    /**
     * Sets the value of the inputContentTraceCARD property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputContentTraceCARD }
     *     
     */
    public void setInputContentTraceCARD(InputContentTraceCARD value) {
        this.inputContentTraceCARD = value;
    }

    /**
     * Gets the value of the inputContentTraceRANGE property.
     * 
     * @return
     *     possible object is
     *     {@link InputContentTraceRANGE }
     *     
     */
    public InputContentTraceRANGE getInputContentTraceRANGE() {
        return inputContentTraceRANGE;
    }

    /**
     * Sets the value of the inputContentTraceRANGE property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputContentTraceRANGE }
     *     
     */
    public void setInputContentTraceRANGE(InputContentTraceRANGE value) {
        this.inputContentTraceRANGE = value;
    }

    /**
     * Gets the value of the inputContentTraceOFF property.
     * 
     * @return
     *     possible object is
     *     {@link InputContentTraceOFF }
     *     
     */
    public InputContentTraceOFF getInputContentTraceOFF() {
        return inputContentTraceOFF;
    }

    /**
     * Sets the value of the inputContentTraceOFF property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputContentTraceOFF }
     *     
     */
    public void setInputContentTraceOFF(InputContentTraceOFF value) {
        this.inputContentTraceOFF = value;
    }

    /**
     * Gets the value of the rulesTraceALL property.
     * 
     * @return
     *     possible object is
     *     {@link RulesTraceALL }
     *     
     */
    public RulesTraceALL getRulesTraceALL() {
        return rulesTraceALL;
    }

    /**
     * Sets the value of the rulesTraceALL property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesTraceALL }
     *     
     */
    public void setRulesTraceALL(RulesTraceALL value) {
        this.rulesTraceALL = value;
    }

    /**
     * Gets the value of the rulesTraceCARD property.
     * 
     * @return
     *     possible object is
     *     {@link RulesTraceCARD }
     *     
     */
    public RulesTraceCARD getRulesTraceCARD() {
        return rulesTraceCARD;
    }

    /**
     * Sets the value of the rulesTraceCARD property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesTraceCARD }
     *     
     */
    public void setRulesTraceCARD(RulesTraceCARD value) {
        this.rulesTraceCARD = value;
    }

    /**
     * Gets the value of the rulesTraceOFF property.
     * 
     * @return
     *     possible object is
     *     {@link RulesTraceOFF }
     *     
     */
    public RulesTraceOFF getRulesTraceOFF() {
        return rulesTraceOFF;
    }

    /**
     * Sets the value of the rulesTraceOFF property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesTraceOFF }
     *     
     */
    public void setRulesTraceOFF(RulesTraceOFF value) {
        this.rulesTraceOFF = value;
    }

    /**
     * Gets the value of the summaryContentTraceON property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryContentTraceON }
     *     
     */
    public SummaryContentTraceON getSummaryContentTraceON() {
        return summaryContentTraceON;
    }

    /**
     * Sets the value of the summaryContentTraceON property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryContentTraceON }
     *     
     */
    public void setSummaryContentTraceON(SummaryContentTraceON value) {
        this.summaryContentTraceON = value;
    }

    /**
     * Gets the value of the summaryContentTraceOFF property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryContentTraceOFF }
     *     
     */
    public SummaryContentTraceOFF getSummaryContentTraceOFF() {
        return summaryContentTraceOFF;
    }

    /**
     * Sets the value of the summaryContentTraceOFF property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryContentTraceOFF }
     *     
     */
    public void setSummaryContentTraceOFF(SummaryContentTraceOFF value) {
        this.summaryContentTraceOFF = value;
    }

    /**
     * Gets the value of the switch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitch() {
        if (_switch == null) {
            return "OFF";
        } else {
            return _switch;
        }
    }

    /**
     * Sets the value of the switch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitch(String value) {
        this._switch = value;
    }

}
