//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}Integral"/>
 *         &lt;element ref="{}Burst"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "integral",
    "burst"
})
@XmlRootElement(name = "FetchAs")
public class FetchAs {

    @XmlElement(name = "Integral")
    protected Integral integral;
    @XmlElement(name = "Burst")
    protected Burst burst;

    /**
     * Gets the value of the integral property.
     * 
     * @return
     *     possible object is
     *     {@link Integral }
     *     
     */
    public Integral getIntegral() {
        return integral;
    }

    /**
     * Sets the value of the integral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integral }
     *     
     */
    public void setIntegral(Integral value) {
        this.integral = value;
    }

    /**
     * Gets the value of the burst property.
     * 
     * @return
     *     possible object is
     *     {@link Burst }
     *     
     */
    public Burst getBurst() {
        return burst;
    }

    /**
     * Sets the value of the burst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Burst }
     *     
     */
    public void setBurst(Burst value) {
        this.burst = value;
    }

}
