//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="StartObject" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EndObject" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "InputContentTrace.RANGE")
public class InputContentTraceRANGE {

    @XmlAttribute(name = "StartObject", required = true)
    protected String startObject;
    @XmlAttribute(name = "EndObject", required = true)
    protected String endObject;

    /**
     * Gets the value of the startObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartObject() {
        return startObject;
    }

    /**
     * Sets the value of the startObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartObject(String value) {
        this.startObject = value;
    }

    /**
     * Gets the value of the endObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndObject() {
        return endObject;
    }

    /**
     * Sets the value of the endObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndObject(String value) {
        this.endObject = value;
    }

}
