//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="workarea" default="Create">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Create"/>
 *             &lt;enumeration value="Reuse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fetchunit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Integral")
public class Integral {

    @XmlAttribute(name = "workarea")
    protected String workarea;
    @XmlAttribute(name = "fetchunit", required = true)
    protected String fetchunit;

    /**
     * Gets the value of the workarea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkarea() {
        if (workarea == null) {
            return "Create";
        } else {
            return workarea;
        }
    }

    /**
     * Sets the value of the workarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkarea(String value) {
        this.workarea = value;
    }

    /**
     * Gets the value of the fetchunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetchunit() {
        return fetchunit;
    }

    /**
     * Sets the value of the fetchunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetchunit(String value) {
        this.fetchunit = value;
    }

}
