//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MapSettings" minOccurs="0"/>
 *         &lt;element ref="{}Remark" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}DataAuditSettings" minOccurs="0"/>
 *         &lt;element ref="{}Input" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Output" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Unresolved" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InputCount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OutputCount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AuditCount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RemarkCount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Runtime" default="WTX">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="WTX"/>
 *             &lt;enumeration value="WDP"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mapSettings",
    "remark",
    "dataAuditSettings",
    "input",
    "output",
    "unresolved"
})
@XmlRootElement(name = "Map")
public class Map {

    @XmlElement(name = "MapSettings")
    protected MapSettings mapSettings;
    @XmlElement(name = "Remark")
    protected List<Remark> remark;
    @XmlElement(name = "DataAuditSettings")
    protected DataAuditSettings dataAuditSettings;
    @XmlElement(name = "Input")
    protected List<Input> input;
    @XmlElement(name = "Output")
    protected List<Output> output;
    @XmlElement(name = "Unresolved")
    protected List<Unresolved> unresolved;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "InputCount", required = true)
    protected String inputCount;
    @XmlAttribute(name = "OutputCount", required = true)
    protected String outputCount;
    @XmlAttribute(name = "AuditCount", required = true)
    protected String auditCount;
    @XmlAttribute(name = "RemarkCount", required = true)
    protected String remarkCount;
    @XmlAttribute(name = "Source")
    protected String source;
    @XmlAttribute(name = "Runtime")
    protected String runtime;

    /**
     * Gets the value of the mapSettings property.
     * 
     * @return
     *     possible object is
     *     {@link MapSettings }
     *     
     */
    public MapSettings getMapSettings() {
        return mapSettings;
    }

    /**
     * Sets the value of the mapSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapSettings }
     *     
     */
    public void setMapSettings(MapSettings value) {
        this.mapSettings = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Remark }
     * 
     * 
     */
    public List<Remark> getRemark() {
        if (remark == null) {
            remark = new ArrayList<Remark>();
        }
        return this.remark;
    }

    /**
     * Gets the value of the dataAuditSettings property.
     * 
     * @return
     *     possible object is
     *     {@link DataAuditSettings }
     *     
     */
    public DataAuditSettings getDataAuditSettings() {
        return dataAuditSettings;
    }

    /**
     * Sets the value of the dataAuditSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAuditSettings }
     *     
     */
    public void setDataAuditSettings(DataAuditSettings value) {
        this.dataAuditSettings = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Input }
     * 
     * 
     */
    public List<Input> getInput() {
        if (input == null) {
            input = new ArrayList<Input>();
        }
        return this.input;
    }

    /**
     * Gets the value of the output property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Output }
     * 
     * 
     */
    public List<Output> getOutput() {
        if (output == null) {
            output = new ArrayList<Output>();
        }
        return this.output;
    }

    /**
     * Gets the value of the unresolved property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unresolved property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnresolved().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Unresolved }
     * 
     * 
     */
    public List<Unresolved> getUnresolved() {
        if (unresolved == null) {
            unresolved = new ArrayList<Unresolved>();
        }
        return this.unresolved;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inputCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputCount() {
        return inputCount;
    }

    /**
     * Sets the value of the inputCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputCount(String value) {
        this.inputCount = value;
    }

    /**
     * Gets the value of the outputCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputCount() {
        return outputCount;
    }

    /**
     * Sets the value of the outputCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputCount(String value) {
        this.outputCount = value;
    }

    /**
     * Gets the value of the auditCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditCount() {
        return auditCount;
    }

    /**
     * Sets the value of the auditCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditCount(String value) {
        this.auditCount = value;
    }

    /**
     * Gets the value of the remarkCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarkCount() {
        return remarkCount;
    }

    /**
     * Sets the value of the remarkCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarkCount(String value) {
        this.remarkCount = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the runtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuntime() {
        if (runtime == null) {
            return "WTX";
        } else {
            return runtime;
        }
    }

    /**
     * Sets the value of the runtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuntime(String value) {
        this.runtime = value;
    }

}
