//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}objectset"/>
 *         &lt;element ref="{}objectrule"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rulenumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objectset",
    "objectrule"
})
@XmlRootElement(name = "MapRule")
public class MapRule {

    @XmlElement(required = true)
    protected String objectset;
    @XmlElement(required = true)
    protected String objectrule;
    @XmlAttribute(name = "rulenumber")
    protected String rulenumber;

    /**
     * Gets the value of the objectset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectset() {
        return objectset;
    }

    /**
     * Sets the value of the objectset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectset(String value) {
        this.objectset = value;
    }

    /**
     * Gets the value of the objectrule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectrule() {
        return objectrule;
    }

    /**
     * Sets the value of the objectrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectrule(String value) {
        this.objectrule = value;
    }

    /**
     * Gets the value of the rulenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRulenumber() {
        return rulenumber;
    }

    /**
     * Sets the value of the rulenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRulenumber(String value) {
        this.rulenumber = value;
    }

}
