//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MapAudit"/>
 *         &lt;element ref="{}MapTrace"/>
 *         &lt;choice>
 *           &lt;element ref="{}WorkSpace.File"/>
 *           &lt;element ref="{}WorkSpace.Memory"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}Century.Current"/>
 *           &lt;element ref="{}Century.Sliding"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}Validation.Standard"/>
 *           &lt;element ref="{}Validation.Custom"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Retry"/>
 *         &lt;choice>
 *           &lt;element ref="{}Warnings.Every"/>
 *           &lt;element ref="{}Warnings.Custom"/>
 *         &lt;/choice>
 *         &lt;element ref="{}CodePageFallback"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mapAudit",
    "mapTrace",
    "workSpaceFile",
    "workSpaceMemory",
    "centuryCurrent",
    "centurySliding",
    "validationStandard",
    "validationCustom",
    "retry",
    "warningsEvery",
    "warningsCustom",
    "codePageFallback"
})
@XmlRootElement(name = "MapSettings")
public class MapSettings {

    @XmlElement(name = "MapAudit", required = true)
    protected MapAudit mapAudit;
    @XmlElement(name = "MapTrace", required = true)
    protected MapTrace mapTrace;
    @XmlElement(name = "WorkSpace.File")
    protected WorkSpaceFile workSpaceFile;
    @XmlElement(name = "WorkSpace.Memory")
    protected WorkSpaceMemory workSpaceMemory;
    @XmlElement(name = "Century.Current")
    protected CenturyCurrent centuryCurrent;
    @XmlElement(name = "Century.Sliding")
    protected CenturySliding centurySliding;
    @XmlElement(name = "Validation.Standard")
    protected ValidationStandard validationStandard;
    @XmlElement(name = "Validation.Custom")
    protected ValidationCustom validationCustom;
    @XmlElement(name = "Retry", required = true)
    protected Retry retry;
    @XmlElement(name = "Warnings.Every")
    protected WarningsEvery warningsEvery;
    @XmlElement(name = "Warnings.Custom")
    protected WarningsCustom warningsCustom;
    @XmlElement(name = "CodePageFallback", required = true)
    protected CodePageFallback codePageFallback;

    /**
     * Gets the value of the mapAudit property.
     * 
     * @return
     *     possible object is
     *     {@link MapAudit }
     *     
     */
    public MapAudit getMapAudit() {
        return mapAudit;
    }

    /**
     * Sets the value of the mapAudit property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapAudit }
     *     
     */
    public void setMapAudit(MapAudit value) {
        this.mapAudit = value;
    }

    /**
     * Gets the value of the mapTrace property.
     * 
     * @return
     *     possible object is
     *     {@link MapTrace }
     *     
     */
    public MapTrace getMapTrace() {
        return mapTrace;
    }

    /**
     * Sets the value of the mapTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapTrace }
     *     
     */
    public void setMapTrace(MapTrace value) {
        this.mapTrace = value;
    }

    /**
     * Gets the value of the workSpaceFile property.
     * 
     * @return
     *     possible object is
     *     {@link WorkSpaceFile }
     *     
     */
    public WorkSpaceFile getWorkSpaceFile() {
        return workSpaceFile;
    }

    /**
     * Sets the value of the workSpaceFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkSpaceFile }
     *     
     */
    public void setWorkSpaceFile(WorkSpaceFile value) {
        this.workSpaceFile = value;
    }

    /**
     * Gets the value of the workSpaceMemory property.
     * 
     * @return
     *     possible object is
     *     {@link WorkSpaceMemory }
     *     
     */
    public WorkSpaceMemory getWorkSpaceMemory() {
        return workSpaceMemory;
    }

    /**
     * Sets the value of the workSpaceMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkSpaceMemory }
     *     
     */
    public void setWorkSpaceMemory(WorkSpaceMemory value) {
        this.workSpaceMemory = value;
    }

    /**
     * Gets the value of the centuryCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link CenturyCurrent }
     *     
     */
    public CenturyCurrent getCenturyCurrent() {
        return centuryCurrent;
    }

    /**
     * Sets the value of the centuryCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenturyCurrent }
     *     
     */
    public void setCenturyCurrent(CenturyCurrent value) {
        this.centuryCurrent = value;
    }

    /**
     * Gets the value of the centurySliding property.
     * 
     * @return
     *     possible object is
     *     {@link CenturySliding }
     *     
     */
    public CenturySliding getCenturySliding() {
        return centurySliding;
    }

    /**
     * Sets the value of the centurySliding property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenturySliding }
     *     
     */
    public void setCenturySliding(CenturySliding value) {
        this.centurySliding = value;
    }

    /**
     * Gets the value of the validationStandard property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationStandard }
     *     
     */
    public ValidationStandard getValidationStandard() {
        return validationStandard;
    }

    /**
     * Sets the value of the validationStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationStandard }
     *     
     */
    public void setValidationStandard(ValidationStandard value) {
        this.validationStandard = value;
    }

    /**
     * Gets the value of the validationCustom property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationCustom }
     *     
     */
    public ValidationCustom getValidationCustom() {
        return validationCustom;
    }

    /**
     * Sets the value of the validationCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationCustom }
     *     
     */
    public void setValidationCustom(ValidationCustom value) {
        this.validationCustom = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link Retry }
     *     
     */
    public Retry getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retry }
     *     
     */
    public void setRetry(Retry value) {
        this.retry = value;
    }

    /**
     * Gets the value of the warningsEvery property.
     * 
     * @return
     *     possible object is
     *     {@link WarningsEvery }
     *     
     */
    public WarningsEvery getWarningsEvery() {
        return warningsEvery;
    }

    /**
     * Sets the value of the warningsEvery property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningsEvery }
     *     
     */
    public void setWarningsEvery(WarningsEvery value) {
        this.warningsEvery = value;
    }

    /**
     * Gets the value of the warningsCustom property.
     * 
     * @return
     *     possible object is
     *     {@link WarningsCustom }
     *     
     */
    public WarningsCustom getWarningsCustom() {
        return warningsCustom;
    }

    /**
     * Sets the value of the warningsCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningsCustom }
     *     
     */
    public void setWarningsCustom(WarningsCustom value) {
        this.warningsCustom = value;
    }

    /**
     * Gets the value of the codePageFallback property.
     * 
     * @return
     *     possible object is
     *     {@link CodePageFallback }
     *     
     */
    public CodePageFallback getCodePageFallback() {
        return codePageFallback;
    }

    /**
     * Sets the value of the codePageFallback property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodePageFallback }
     *     
     */
    public void setCodePageFallback(CodePageFallback value) {
        this.codePageFallback = value;
    }

}
