//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.wtxEXP package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnresolvedName_QNAME = new QName("", "UnresolvedName");
    private final static QName _Objectrule_QNAME = new QName("", "objectrule");
    private final static QName _FilePath_QNAME = new QName("", "FilePath");
    private final static QName _UnresolvedRule_QNAME = new QName("", "UnresolvedRule");
    private final static QName _SyntaxCard_QNAME = new QName("", "SyntaxCard");
    private final static QName _DirectoryCustom_QNAME = new QName("", "Directory.Custom");
    private final static QName _Objectset_QNAME = new QName("", "objectset");
    private final static QName _MetaDataLocation_QNAME = new QName("", "MetaDataLocation");
    private final static QName _DocumentVerification_QNAME = new QName("", "DocumentVerification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.wtxEXP
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidationCustom }
     * 
     */
    public ValidationCustom createValidationCustom() {
        return new ValidationCustom();
    }

    /**
     * Create an instance of {@link InputContentTraceRANGE }
     * 
     */
    public InputContentTraceRANGE createInputContentTraceRANGE() {
        return new InputContentTraceRANGE();
    }

    /**
     * Create an instance of {@link FileNameUnique }
     * 
     */
    public FileNameUnique createFileNameUnique() {
        return new FileNameUnique();
    }

    /**
     * Create an instance of {@link MapSettings }
     * 
     */
    public MapSettings createMapSettings() {
        return new MapSettings();
    }

    /**
     * Create an instance of {@link MapAudit }
     * 
     */
    public MapAudit createMapAudit() {
        return new MapAudit();
    }

    /**
     * Create an instance of {@link BurstAudit }
     * 
     */
    public BurstAudit createBurstAudit() {
        return new BurstAudit();
    }

    /**
     * Create an instance of {@link DataAlways }
     * 
     */
    public DataAlways createDataAlways() {
        return new DataAlways();
    }

    /**
     * Create an instance of {@link DataNever }
     * 
     */
    public DataNever createDataNever() {
        return new DataNever();
    }

    /**
     * Create an instance of {@link DataOnBurstError }
     * 
     */
    public DataOnBurstError createDataOnBurstError() {
        return new DataOnBurstError();
    }

    /**
     * Create an instance of {@link DataOnBurstWarningOrError }
     * 
     */
    public DataOnBurstWarningOrError createDataOnBurstWarningOrError() {
        return new DataOnBurstWarningOrError();
    }

    /**
     * Create an instance of {@link ExecutionAlways }
     * 
     */
    public ExecutionAlways createExecutionAlways() {
        return new ExecutionAlways();
    }

    /**
     * Create an instance of {@link ExecutionNever }
     * 
     */
    public ExecutionNever createExecutionNever() {
        return new ExecutionNever();
    }

    /**
     * Create an instance of {@link ExecutionOnBurstError }
     * 
     */
    public ExecutionOnBurstError createExecutionOnBurstError() {
        return new ExecutionOnBurstError();
    }

    /**
     * Create an instance of {@link ExecutionOnBurstWarningOrError }
     * 
     */
    public ExecutionOnBurstWarningOrError createExecutionOnBurstWarningOrError() {
        return new ExecutionOnBurstWarningOrError();
    }

    /**
     * Create an instance of {@link SummaryAudit }
     * 
     */
    public SummaryAudit createSummaryAudit() {
        return new SummaryAudit();
    }

    /**
     * Create an instance of {@link SettingsAudit }
     * 
     */
    public SettingsAudit createSettingsAudit() {
        return new SettingsAudit();
    }

    /**
     * Create an instance of {@link AuditLocationFile }
     * 
     */
    public AuditLocationFile createAuditLocationFile() {
        return new AuditLocationFile();
    }

    /**
     * Create an instance of {@link DirectoryMap }
     * 
     */
    public DirectoryMap createDirectoryMap() {
        return new DirectoryMap();
    }

    /**
     * Create an instance of {@link FileNameDefault }
     * 
     */
    public FileNameDefault createFileNameDefault() {
        return new FileNameDefault();
    }

    /**
     * Create an instance of {@link FileNameCustom }
     * 
     */
    public FileNameCustom createFileNameCustom() {
        return new FileNameCustom();
    }

    /**
     * Create an instance of {@link AuditLocationMemory }
     * 
     */
    public AuditLocationMemory createAuditLocationMemory() {
        return new AuditLocationMemory();
    }

    /**
     * Create an instance of {@link MapTrace }
     * 
     */
    public MapTrace createMapTrace() {
        return new MapTrace();
    }

    /**
     * Create an instance of {@link ContentTraceFile }
     * 
     */
    public ContentTraceFile createContentTraceFile() {
        return new ContentTraceFile();
    }

    /**
     * Create an instance of {@link TraceLocationFile }
     * 
     */
    public TraceLocationFile createTraceLocationFile() {
        return new TraceLocationFile();
    }

    /**
     * Create an instance of {@link InputContentTraceALL }
     * 
     */
    public InputContentTraceALL createInputContentTraceALL() {
        return new InputContentTraceALL();
    }

    /**
     * Create an instance of {@link InputContentTraceCARD }
     * 
     */
    public InputContentTraceCARD createInputContentTraceCARD() {
        return new InputContentTraceCARD();
    }

    /**
     * Create an instance of {@link InputContentTraceOFF }
     * 
     */
    public InputContentTraceOFF createInputContentTraceOFF() {
        return new InputContentTraceOFF();
    }

    /**
     * Create an instance of {@link RulesTraceALL }
     * 
     */
    public RulesTraceALL createRulesTraceALL() {
        return new RulesTraceALL();
    }

    /**
     * Create an instance of {@link RulesTraceCARD }
     * 
     */
    public RulesTraceCARD createRulesTraceCARD() {
        return new RulesTraceCARD();
    }

    /**
     * Create an instance of {@link RulesTraceOFF }
     * 
     */
    public RulesTraceOFF createRulesTraceOFF() {
        return new RulesTraceOFF();
    }

    /**
     * Create an instance of {@link SummaryContentTraceON }
     * 
     */
    public SummaryContentTraceON createSummaryContentTraceON() {
        return new SummaryContentTraceON();
    }

    /**
     * Create an instance of {@link SummaryContentTraceOFF }
     * 
     */
    public SummaryContentTraceOFF createSummaryContentTraceOFF() {
        return new SummaryContentTraceOFF();
    }

    /**
     * Create an instance of {@link WorkSpaceFile }
     * 
     */
    public WorkSpaceFile createWorkSpaceFile() {
        return new WorkSpaceFile();
    }

    /**
     * Create an instance of {@link WorkFilePrefixMapName }
     * 
     */
    public WorkFilePrefixMapName createWorkFilePrefixMapName() {
        return new WorkFilePrefixMapName();
    }

    /**
     * Create an instance of {@link WorkFilePrefixUnique }
     * 
     */
    public WorkFilePrefixUnique createWorkFilePrefixUnique() {
        return new WorkFilePrefixUnique();
    }

    /**
     * Create an instance of {@link WorkSpaceMemory }
     * 
     */
    public WorkSpaceMemory createWorkSpaceMemory() {
        return new WorkSpaceMemory();
    }

    /**
     * Create an instance of {@link CenturyCurrent }
     * 
     */
    public CenturyCurrent createCenturyCurrent() {
        return new CenturyCurrent();
    }

    /**
     * Create an instance of {@link CenturySliding }
     * 
     */
    public CenturySliding createCenturySliding() {
        return new CenturySliding();
    }

    /**
     * Create an instance of {@link ValidationStandard }
     * 
     */
    public ValidationStandard createValidationStandard() {
        return new ValidationStandard();
    }

    /**
     * Create an instance of {@link Retry }
     * 
     */
    public Retry createRetry() {
        return new Retry();
    }

    /**
     * Create an instance of {@link WarningsEvery }
     * 
     */
    public WarningsEvery createWarningsEvery() {
        return new WarningsEvery();
    }

    /**
     * Create an instance of {@link WarningsCustom }
     * 
     */
    public WarningsCustom createWarningsCustom() {
        return new WarningsCustom();
    }

    /**
     * Create an instance of {@link CodePageFallback }
     * 
     */
    public CodePageFallback createCodePageFallback() {
        return new CodePageFallback();
    }

    /**
     * Create an instance of {@link FILETargetTransaction }
     * 
     */
    public FILETargetTransaction createFILETargetTransaction() {
        return new FILETargetTransaction();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link NameSpaces }
     * 
     */
    public NameSpaces createNameSpaces() {
        return new NameSpaces();
    }

    /**
     * Create an instance of {@link TargetRule }
     * 
     */
    public TargetRule createTargetRule() {
        return new TargetRule();
    }

    /**
     * Create an instance of {@link PUT }
     * 
     */
    public PUT createPUT() {
        return new PUT();
    }

    /**
     * Create an instance of {@link FILETarget }
     * 
     */
    public FILETarget createFILETarget() {
        return new FILETarget();
    }

    /**
     * Create an instance of {@link Backup }
     * 
     */
    public Backup createBackup() {
        return new Backup();
    }

    /**
     * Create an instance of {@link BackupLocationFile }
     * 
     */
    public BackupLocationFile createBackupLocationFile() {
        return new BackupLocationFile();
    }

    /**
     * Create an instance of {@link MapRule }
     * 
     */
    public MapRule createMapRule() {
        return new MapRule();
    }

    /**
     * Create an instance of {@link FetchAs }
     * 
     */
    public FetchAs createFetchAs() {
        return new FetchAs();
    }

    /**
     * Create an instance of {@link Integral }
     * 
     */
    public Integral createIntegral() {
        return new Integral();
    }

    /**
     * Create an instance of {@link Burst }
     * 
     */
    public Burst createBurst() {
        return new Burst();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Remark }
     * 
     */
    public Remark createRemark() {
        return new Remark();
    }

    /**
     * Create an instance of {@link DataAuditSettings }
     * 
     */
    public DataAuditSettings createDataAuditSettings() {
        return new DataAuditSettings();
    }

    /**
     * Create an instance of {@link AuditObject }
     * 
     */
    public AuditObject createAuditObject() {
        return new AuditObject();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link NativeXSDCustomization }
     * 
     */
    public NativeXSDCustomization createNativeXSDCustomization() {
        return new NativeXSDCustomization();
    }

    /**
     * Create an instance of {@link SourceRule }
     * 
     */
    public SourceRule createSourceRule() {
        return new SourceRule();
    }

    /**
     * Create an instance of {@link GET }
     * 
     */
    public GET createGET() {
        return new GET();
    }

    /**
     * Create an instance of {@link FILESource }
     * 
     */
    public FILESource createFILESource() {
        return new FILESource();
    }

    /**
     * Create an instance of {@link FILESourceTransaction }
     * 
     */
    public FILESourceTransaction createFILESourceTransaction() {
        return new FILESourceTransaction();
    }

    /**
     * Create an instance of {@link Unresolved }
     * 
     */
    public Unresolved createUnresolved() {
        return new Unresolved();
    }

    /**
     * Create an instance of {@link MMS }
     * 
     */
    public MMS createMMS() {
        return new MMS();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnresolvedName")
    public JAXBElement<String> createUnresolvedName(String value) {
        return new JAXBElement<String>(_UnresolvedName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "objectrule")
    public JAXBElement<String> createObjectrule(String value) {
        return new JAXBElement<String>(_Objectrule_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FilePath")
    public JAXBElement<String> createFilePath(String value) {
        return new JAXBElement<String>(_FilePath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnresolvedRule")
    public JAXBElement<String> createUnresolvedRule(String value) {
        return new JAXBElement<String>(_UnresolvedRule_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SyntaxCard")
    public JAXBElement<String> createSyntaxCard(String value) {
        return new JAXBElement<String>(_SyntaxCard_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Directory.Custom")
    public JAXBElement<String> createDirectoryCustom(String value) {
        return new JAXBElement<String>(_DirectoryCustom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "objectset")
    public JAXBElement<String> createObjectset(String value) {
        return new JAXBElement<String>(_Objectset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MetaDataLocation")
    public JAXBElement<String> createMetaDataLocation(String value) {
        return new JAXBElement<String>(_MetaDataLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentVerification")
    public JAXBElement<String> createDocumentVerification(String value) {
        return new JAXBElement<String>(_DocumentVerification_QNAME, String.class, null, value);
    }

}
