//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Schema"/>
 *         &lt;element ref="{}NameSpaces"/>
 *         &lt;element ref="{}TargetRule"/>
 *         &lt;element ref="{}SyntaxCard"/>
 *         &lt;element ref="{}MapRule" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schema",
    "nameSpaces",
    "targetRule",
    "syntaxCard",
    "mapRule"
})
@XmlRootElement(name = "Output")
public class Output {

    @XmlElement(name = "Schema", required = true)
    protected Schema schema;
    @XmlElement(name = "NameSpaces", required = true)
    protected NameSpaces nameSpaces;
    @XmlElement(name = "TargetRule", required = true)
    protected TargetRule targetRule;
    @XmlElement(name = "SyntaxCard", required = true)
    protected String syntaxCard;
    @XmlElement(name = "MapRule", required = true)
    protected List<MapRule> mapRule;

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link Schema }
     *     
     */
    public Schema getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schema }
     *     
     */
    public void setSchema(Schema value) {
        this.schema = value;
    }

    /**
     * Gets the value of the nameSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link NameSpaces }
     *     
     */
    public NameSpaces getNameSpaces() {
        return nameSpaces;
    }

    /**
     * Sets the value of the nameSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameSpaces }
     *     
     */
    public void setNameSpaces(NameSpaces value) {
        this.nameSpaces = value;
    }

    /**
     * Gets the value of the targetRule property.
     * 
     * @return
     *     possible object is
     *     {@link TargetRule }
     *     
     */
    public TargetRule getTargetRule() {
        return targetRule;
    }

    /**
     * Sets the value of the targetRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetRule }
     *     
     */
    public void setTargetRule(TargetRule value) {
        this.targetRule = value;
    }

    /**
     * Gets the value of the syntaxCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyntaxCard() {
        return syntaxCard;
    }

    /**
     * Sets the value of the syntaxCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyntaxCard(String value) {
        this.syntaxCard = value;
    }

    /**
     * Gets the value of the mapRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapRule }
     * 
     * 
     */
    public List<MapRule> getMapRule() {
        if (mapRule == null) {
            mapRule = new ArrayList<MapRule>();
        }
        return this.mapRule;
    }

}
