//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FILE_Target"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileTarget"
})
@XmlRootElement(name = "PUT")
public class PUT {

    @XmlElement(name = "FILE_Target", required = true)
    protected FILETarget fileTarget;

    /**
     * Gets the value of the fileTarget property.
     * 
     * @return
     *     possible object is
     *     {@link FILETarget }
     *     
     */
    public FILETarget getFILETarget() {
        return fileTarget;
    }

    /**
     * Sets the value of the fileTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link FILETarget }
     *     
     */
    public void setFILETarget(FILETarget value) {
        this.fileTarget = value;
    }

}
