//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cardnumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cardname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typetree" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Schema")
public class Schema {

    @XmlAttribute(name = "cardnumber", required = true)
    protected String cardnumber;
    @XmlAttribute(name = "cardname", required = true)
    protected String cardname;
    @XmlAttribute(name = "typetree", required = true)
    protected String typetree;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the cardnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * Sets the value of the cardnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardnumber(String value) {
        this.cardnumber = value;
    }

    /**
     * Gets the value of the cardname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardname() {
        return cardname;
    }

    /**
     * Sets the value of the cardname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardname(String value) {
        this.cardname = value;
    }

    /**
     * Gets the value of the typetree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypetree() {
        return typetree;
    }

    /**
     * Sets the value of the typetree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypetree(String value) {
        this.typetree = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
