//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="OnValidationError" default="Continue">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Continue"/>
 *             &lt;enumeration value="Stop"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RestrictionError" default="Validate">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Validate"/>
 *             &lt;enumeration value="IgnoreNoWarnings"/>
 *             &lt;enumeration value="Ignore"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SizeError" default="Validate">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Validate"/>
 *             &lt;enumeration value="Ignore"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PresentationError" default="Validate">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Validate"/>
 *             &lt;enumeration value="Ignore"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Validation.Custom")
public class ValidationCustom {

    @XmlAttribute(name = "OnValidationError")
    protected String onValidationError;
    @XmlAttribute(name = "RestrictionError")
    protected String restrictionError;
    @XmlAttribute(name = "SizeError")
    protected String sizeError;
    @XmlAttribute(name = "PresentationError")
    protected String presentationError;

    /**
     * Gets the value of the onValidationError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnValidationError() {
        if (onValidationError == null) {
            return "Continue";
        } else {
            return onValidationError;
        }
    }

    /**
     * Sets the value of the onValidationError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnValidationError(String value) {
        this.onValidationError = value;
    }

    /**
     * Gets the value of the restrictionError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictionError() {
        if (restrictionError == null) {
            return "Validate";
        } else {
            return restrictionError;
        }
    }

    /**
     * Sets the value of the restrictionError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictionError(String value) {
        this.restrictionError = value;
    }

    /**
     * Gets the value of the sizeError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeError() {
        if (sizeError == null) {
            return "Validate";
        } else {
            return sizeError;
        }
    }

    /**
     * Sets the value of the sizeError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeError(String value) {
        this.sizeError = value;
    }

    /**
     * Gets the value of the presentationError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationError() {
        if (presentationError == null) {
            return "Validate";
        } else {
            return presentationError;
        }
    }

    /**
     * Sets the value of the presentationError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationError(String value) {
        this.presentationError = value;
    }

}
