//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:11:46 PM AEDT 
//


package com.ibm.wtxEXP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="OneOrMoreOutputsWasInvalid" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PageUseCountError" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="InputValidButUnknownDataFound" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OutputTypeInError" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OutputTypeContainsError" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="InputTypeContainsError" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OutputValidButUnknownDataFound" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TooFewPagesRequestedMoreAllocated" default="warn">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ignore"/>
 *             &lt;enumeration value="fail"/>
 *             &lt;enumeration value="warn"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Warnings.Custom")
public class WarningsCustom {

    @XmlAttribute(name = "OneOrMoreOutputsWasInvalid")
    protected String oneOrMoreOutputsWasInvalid;
    @XmlAttribute(name = "PageUseCountError")
    protected String pageUseCountError;
    @XmlAttribute(name = "InputValidButUnknownDataFound")
    protected String inputValidButUnknownDataFound;
    @XmlAttribute(name = "OutputTypeInError")
    protected String outputTypeInError;
    @XmlAttribute(name = "OutputTypeContainsError")
    protected String outputTypeContainsError;
    @XmlAttribute(name = "InputTypeContainsError")
    protected String inputTypeContainsError;
    @XmlAttribute(name = "OutputValidButUnknownDataFound")
    protected String outputValidButUnknownDataFound;
    @XmlAttribute(name = "TooFewPagesRequestedMoreAllocated")
    protected String tooFewPagesRequestedMoreAllocated;

    /**
     * Gets the value of the oneOrMoreOutputsWasInvalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOneOrMoreOutputsWasInvalid() {
        if (oneOrMoreOutputsWasInvalid == null) {
            return "warn";
        } else {
            return oneOrMoreOutputsWasInvalid;
        }
    }

    /**
     * Sets the value of the oneOrMoreOutputsWasInvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOneOrMoreOutputsWasInvalid(String value) {
        this.oneOrMoreOutputsWasInvalid = value;
    }

    /**
     * Gets the value of the pageUseCountError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageUseCountError() {
        if (pageUseCountError == null) {
            return "warn";
        } else {
            return pageUseCountError;
        }
    }

    /**
     * Sets the value of the pageUseCountError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageUseCountError(String value) {
        this.pageUseCountError = value;
    }

    /**
     * Gets the value of the inputValidButUnknownDataFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputValidButUnknownDataFound() {
        if (inputValidButUnknownDataFound == null) {
            return "warn";
        } else {
            return inputValidButUnknownDataFound;
        }
    }

    /**
     * Sets the value of the inputValidButUnknownDataFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputValidButUnknownDataFound(String value) {
        this.inputValidButUnknownDataFound = value;
    }

    /**
     * Gets the value of the outputTypeInError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputTypeInError() {
        if (outputTypeInError == null) {
            return "warn";
        } else {
            return outputTypeInError;
        }
    }

    /**
     * Sets the value of the outputTypeInError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputTypeInError(String value) {
        this.outputTypeInError = value;
    }

    /**
     * Gets the value of the outputTypeContainsError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputTypeContainsError() {
        if (outputTypeContainsError == null) {
            return "warn";
        } else {
            return outputTypeContainsError;
        }
    }

    /**
     * Sets the value of the outputTypeContainsError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputTypeContainsError(String value) {
        this.outputTypeContainsError = value;
    }

    /**
     * Gets the value of the inputTypeContainsError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputTypeContainsError() {
        if (inputTypeContainsError == null) {
            return "warn";
        } else {
            return inputTypeContainsError;
        }
    }

    /**
     * Sets the value of the inputTypeContainsError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputTypeContainsError(String value) {
        this.inputTypeContainsError = value;
    }

    /**
     * Gets the value of the outputValidButUnknownDataFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputValidButUnknownDataFound() {
        if (outputValidButUnknownDataFound == null) {
            return "warn";
        } else {
            return outputValidButUnknownDataFound;
        }
    }

    /**
     * Sets the value of the outputValidButUnknownDataFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputValidButUnknownDataFound(String value) {
        this.outputValidButUnknownDataFound = value;
    }

    /**
     * Gets the value of the tooFewPagesRequestedMoreAllocated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooFewPagesRequestedMoreAllocated() {
        if (tooFewPagesRequestedMoreAllocated == null) {
            return "warn";
        } else {
            return tooFewPagesRequestedMoreAllocated;
        }
    }

    /**
     * Sets the value of the tooFewPagesRequestedMoreAllocated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooFewPagesRequestedMoreAllocated(String value) {
        this.tooFewPagesRequestedMoreAllocated = value;
    }

}
